name: spring-cloud
services:

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-broker
    environment:
      - MONGODB_ROOT_PASSWORD=abc123456 # Đặt mật khẩu root cho MongoDB
      - MONGODB_USER=user # Đặt tên người dùng cho MongoDB
      - MONGODB_PASSWORD=ad123456 # Đặt mật khẩu cho người dùng MongoDB
      - MONGODB_DATABASE=cloud  # Đặt database mặc định
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/bitnami/mongodb/data

  redis:
    image: redis:7.2
    container_name: redis-broker
    command: [ "redis-server" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data



volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
