version: "3"
name: spring-cloud
services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER


  mongodb:
    image: bitnami/mongodb:7.0.11
    container_name: mongodb-broker
    environment:
      - MONGODB_ROOT_PASSWORD=abc123456 # Đặt mật khẩu root cho MongoDB
      - MONGODB_USER=user # Đặt tên người dùng cho MongoDB
      - MONGODB_PASSWORD=ad123456 # Đặt mật khẩu cho người dùng MongoDB
      - MONGODB_DATABASE=cloud  # Đặt database mặc định
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/bitnami/mongodb/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch-broker
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - '9200:9200'  # Cổng HTTP mặc định
      - '9300:9300'  # Cổng TCP transport mặc định
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana-broker
    ports: [ '5601:5601' ]
    depends_on: [ 'elasticsearch' ]

  redis:
    image: redis:7.2
    container_name: redis-broker
    command: [ "redis-server" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data



volumes:
  neo4j-data:
    driver: local
  mongodb-data:
    driver: local
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local
