server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leduy2004-coder/spring-cloud-config-repo.git
          default-label: master
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
